name: Docker Build and Push
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: lfreea
          password: dckr_pat_BlsimazCtkseQEMrA_qcDDr56D0

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: lfreea/tokenpay:latest, lfreea/tokenpay:${{ github.sha }}
          build-args: |
            SOME_ARG=${{ secrets.SOME_SECRET }}
